telosysaas_mongodb:
  image: mongo:latest
  command: mongod --storageEngine=wiredTiger
  
telosysaas_tomcat:
  image: telosystoolssaas/back
  ports:
    - "10080:8080"
  links:
    - telosysaas_mongodb
